-- 魔女小店数据库结构
-- 安装程序会在执行前将 {prefix} 替换为实际表前缀

CREATE TABLE IF NOT EXISTS {prefix}admin_users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL,
    name VARCHAR(80) NOT NULL DEFAULT '',
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'admin',
    status TINYINT(1) NOT NULL DEFAULT 1,
    last_login_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_admin_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {prefix}users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) DEFAULT NULL,
    name VARCHAR(80) NOT NULL,
    email VARCHAR(120) DEFAULT NULL,
    password_hash VARCHAR(255) DEFAULT NULL,
    reset_token VARCHAR(128) DEFAULT NULL,
    reset_expires DATETIME DEFAULT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    level VARCHAR(30) NOT NULL DEFAULT 'member',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    address TEXT,
    last_login DATETIME DEFAULT NULL,
    note TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_username (username),
    UNIQUE KEY uk_users_email (email),
    KEY idx_users_reset_token (reset_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {prefix}categories (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(80) NOT NULL,
    description TEXT,
    accent VARCHAR(20) NOT NULL DEFAULT '#cbd5e1',
    emoji VARCHAR(10) NOT NULL DEFAULT '*',
    sort INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {prefix}products (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(80) NOT NULL DEFAULT '未分类',
    sales INT NOT NULL DEFAULT 0,
    price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    stock INT NOT NULL DEFAULT 0,
    tag VARCHAR(50) NOT NULL DEFAULT '',
    home_sort INT NOT NULL DEFAULT 0,
    page_sort INT NOT NULL DEFAULT 0,
    sku TEXT,
    cover_image VARCHAR(255) DEFAULT NULL,
    images TEXT DEFAULT NULL,
    description TEXT DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'on_sale',
    published_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {prefix}orders (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_no VARCHAR(32) NOT NULL,
    user_id INT UNSIGNED DEFAULT NULL,
    customer VARCHAR(80) DEFAULT NULL,
    phone VARCHAR(20) DEFAULT NULL,
    address TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    pay_method VARCHAR(20) DEFAULT NULL,
    express_company VARCHAR(80) DEFAULT '',
    tracking_numbers TEXT DEFAULT NULL,
    items TEXT DEFAULT NULL,
    total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    remark VARCHAR(255) DEFAULT NULL,
    time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_orders_order_no (order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS {prefix}settings (
    `key` VARCHAR(50) NOT NULL,
    `value` TEXT,
    PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
